# Generated by Django 3.1.7 on 2021-03-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaprod',
            old_name='update',
            new_name='updated',
        ),
    ]
